import { User, Post, Notification, Badge } from "../types";

export const DEFAULT_BADGES: Badge[] = [
  {
    id: "badge-1",
    name: "Professional Roaster",
    description: "Submitted over 25 savagely upvoted roasts",
    icon: "🔥",
    tier: "crimson",
    unlockedAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "badge-2",
    name: "Heartbreak Veteran",
    description: "Survived dramatic exes and turned pain into comedy",
    icon: "💔",
    tier: "gold",
    unlockedAt: "2026-01-20T12:30:00Z",
  },
  {
    id: "badge-3",
    name: "Roast King",
    description: "Won #1 Roast of the Day multiple times",
    icon: "👑",
    tier: "crimson",
    unlockedAt: "2026-02-01T15:00:00Z",
  },
  {
    id: "badge-4",
    name: "Emotionally Unavailable",
    description: "Untouchable immune system to manipulation",
    icon: "🧊",
    tier: "silver",
    unlockedAt: "2026-02-10T18:00:00Z",
  },
  {
    id: "badge-5",
    name: "Red Flag Radar",
    description: "Spotted red flags from 10 miles away",
    icon: "🚩",
    tier: "gold",
    unlockedAt: "2026-02-14T09:00:00Z",
  },
];

export const SEED_USERS: User[] = [
  {
    id: "user-1",
    username: "HeartbreakDealer",
    displayName: "Elena Vance",
    email: "elena@exroast.com",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
    bio: "Turning relationship trauma into comedy gold. Unapologetically unfiltered.",
    relationshipStatus: "Happily Single & Thriving",
    roastPoints: 4820,
    followersCount: 1420,
    followingCount: 180,
    postsCount: 12,
    roastsCount: 88,
    winsCount: 14,
    badges: [DEFAULT_BADGES[0], DEFAULT_BADGES[1], DEFAULT_BADGES[2]],
    createdAt: "2025-11-10T08:00:00Z",
    isVerified: true,
  },
  {
    id: "user-2",
    username: "NoMercy",
    displayName: "Marcus King",
    email: "marcus@exroast.com",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    bio: "Delivering devastating one-liners since 2020. No ex is safe from the truth.",
    relationshipStatus: "In a committed relationship with peace of mind",
    roastPoints: 6350,
    followersCount: 2980,
    followingCount: 210,
    postsCount: 8,
    roastsCount: 142,
    winsCount: 29,
    badges: [DEFAULT_BADGES[0], DEFAULT_BADGES[2], DEFAULT_BADGES[3]],
    createdAt: "2025-10-01T04:00:00Z",
    isVerified: true,
  },
  {
    id: "user-3",
    username: "SavageSam",
    displayName: "Samantha Reed",
    email: "sam@exroast.com",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80",
    bio: "Exes are like bad tattoos: expensive, painful, and funny in hindsight.",
    relationshipStatus: "Observing from a safe distance",
    roastPoints: 5120,
    followersCount: 1850,
    followingCount: 310,
    postsCount: 15,
    roastsCount: 96,
    winsCount: 18,
    badges: [DEFAULT_BADGES[0], DEFAULT_BADGES[4]],
    createdAt: "2025-12-05T09:20:00Z",
    isVerified: true,
  },
  {
    id: "user-4",
    username: "Cooked",
    displayName: "Leo Romero",
    email: "leo@exroast.com",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
    bio: "If you didn't laugh, you'd cry. So we roast.",
    relationshipStatus: "Single and enjoying my heated seats alone",
    roastPoints: 3890,
    followersCount: 940,
    followingCount: 140,
    postsCount: 6,
    roastsCount: 74,
    winsCount: 11,
    badges: [DEFAULT_BADGES[1], DEFAULT_BADGES[3]],
    createdAt: "2026-01-02T11:00:00Z",
    isVerified: false,
  },
  {
    id: "user-5",
    username: "RedFlagHunter",
    displayName: "Chloe Bennett",
    email: "chloe@exroast.com",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80",
    bio: "I see red flags in 8K resolution before they even say hello.",
    relationshipStatus: "Healing and collecting receipts",
    roastPoints: 3410,
    followersCount: 1120,
    followingCount: 420,
    postsCount: 19,
    roastsCount: 52,
    winsCount: 9,
    badges: [DEFAULT_BADGES[4]],
    createdAt: "2026-01-18T14:40:00Z",
    isVerified: false,
  },
];

export const SEED_POSTS: Post[] = [
  {
    id: "post-1",
    authorId: "user-1",
    authorUsername: "HeartbreakDealer",
    authorDisplayName: "Elena Vance",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
    isAnonymous: false,
    title: "Told me they weren't ready for a relationship...",
    content: "My ex looked me dead in the eyes over dinner and said they 'deeply loved me but had too much personal trauma to be in any relationship right now.' Exactly 48 hours later, they hard-launched their official Facebook and Instagram relationship status with someone they met on LinkedIn.",
    category: "Dumb Excuse",
    imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80",
    hashtags: ["DumbExcuse", "LinkedInLover", "ClownBehavior", "ExFiles"],
    createdAt: new Date(Date.now() - 3600 * 1000 * 3).toISOString(), // 3h ago
    reactions: { savage: 842, dead: 1205, redFlag: 640, deserved: 195 },
    userReaction: "dead",
    roastsCount: 4,
    commentsCount: 38,
    savesCount: 341,
    sharesCount: 189,
    userSaved: true,
    flameScore: 3200,
    roasts: [
      {
        id: "roast-101",
        postId: "post-1",
        authorId: "user-2",
        authorUsername: "NoMercy",
        authorDisplayName: "Marcus King",
        authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
        content: "Bro wasn't unready for a relationship. He was unready for YOUR standards and went on LinkedIn to network for a lateral downgrade.",
        score: 642,
        upvotes: 660,
        downvotes: 18,
        createdAt: new Date(Date.now() - 3600 * 1000 * 2.5).toISOString(),
        userVote: "up",
        isTopRoast: true,
        isRoastOfTheDay: true,
      },
      {
        id: "roast-102",
        postId: "post-1",
        authorId: "user-3",
        authorUsername: "SavageSam",
        authorDisplayName: "Samantha Reed",
        authorAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80",
        content: "Meeting someone on LinkedIn is crazy. Their wedding vows are gonna include 'Key Performance Indicators' and synergy.",
        score: 418,
        upvotes: 430,
        downvotes: 12,
        createdAt: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
      },
      {
        id: "roast-103",
        postId: "post-1",
        authorId: "user-4",
        authorUsername: "Cooked",
        authorDisplayName: "Leo Romero",
        authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
        content: "Trauma cured in 48 hours? Drop the therapist's number because that's a medical miracle.",
        score: 289,
        upvotes: 295,
        downvotes: 6,
        createdAt: new Date(Date.now() - 3600 * 1000 * 1.5).toISOString(),
      },
    ],
    comments: [
      {
        id: "comm-1",
        postId: "post-1",
        authorId: "user-5",
        authorUsername: "RedFlagHunter",
        authorDisplayName: "Chloe Bennett",
        authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80",
        content: "LinkedIn networking turned romantic is the most corporate villain origin story I've ever heard.",
        createdAt: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
        likes: 45,
        replies: [
          {
            id: "reply-1",
            commentId: "comm-1",
            authorId: "user-1",
            authorUsername: "HeartbreakDealer",
            authorDisplayName: "Elena Vance",
            authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
            content: "Right?? I hope their relationship has quarterly performance reviews! 😂",
            createdAt: new Date(Date.now() - 3600 * 1000 * 1.8).toISOString(),
            likes: 22,
          }
        ]
      }
    ]
  },
  {
    id: "post-2",
    authorId: "user-99",
    authorUsername: "anonymous_survivor",
    authorDisplayName: "Anonymous",
    authorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80",
    isAnonymous: true,
    anonymousAlias: "The Space Cadet",
    title: "Apparently she needed 'space'...",
    content: "We dated for two years. She said she felt suffocated and needed 'infinite space and tranquility to find her inner core.' I found out last week she moved in with her co-worker three blocks away from my apartment.",
    category: "Ghosting",
    hashtags: ["NeededSpace", "NASA", "Audacity", "ExTales"],
    createdAt: new Date(Date.now() - 3600 * 1000 * 8).toISOString(),
    reactions: { savage: 1420, dead: 2150, redFlag: 890, deserved: 310 },
    userReaction: "savage",
    roastsCount: 3,
    commentsCount: 52,
    savesCount: 512,
    sharesCount: 290,
    userSaved: false,
    flameScore: 4800,
    roasts: [
      {
        id: "roast-201",
        postId: "post-2",
        authorId: "user-3",
        authorUsername: "SavageSam",
        authorDisplayName: "Samantha Reed",
        authorAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80",
        content: "NASA called. They searched the entire Milky Way and found her inner core was just a spare bedroom at Greg's place.",
        score: 892,
        upvotes: 910,
        downvotes: 18,
        createdAt: new Date(Date.now() - 3600 * 1000 * 7).toISOString(),
        isTopRoast: true,
      },
      {
        id: "roast-202",
        postId: "post-2",
        authorId: "user-2",
        authorUsername: "NoMercy",
        authorDisplayName: "Marcus King",
        authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
        content: "Three blocks away isn't space, that's just a light jog and a restraining order.",
        score: 540,
        upvotes: 555,
        downvotes: 15,
        createdAt: new Date(Date.now() - 3600 * 1000 * 6.5).toISOString(),
      },
    ],
    comments: [],
  },
  {
    id: "post-3",
    authorId: "user-5",
    authorUsername: "RedFlagHunter",
    authorDisplayName: "Chloe Bennett",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80",
    isAnonymous: false,
    title: "Split the birthday bill down to the cent, but forgot his wallet",
    content: "He insisted on taking me to a Michelin-star restaurant for my 25th birthday. When the $420 bill came, he pulled out his phone calculator, divided the tax, subtracted the bread basket because 'he only ate one piece', and then confessed he accidentally left his Amex at home.",
    category: "Money",
    imageUrl: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800&auto=format&fit=crop&q=80",
    hashtags: ["CheapSkate", "BirthdayRuined", "BrokeBehavior", "WorstDate"],
    createdAt: new Date(Date.now() - 3600 * 1000 * 14).toISOString(),
    reactions: { savage: 1890, dead: 2400, redFlag: 1980, deserved: 120 },
    userReaction: "redFlag",
    roastsCount: 3,
    commentsCount: 64,
    savesCount: 680,
    sharesCount: 410,
    flameScore: 5600,
    roasts: [
      {
        id: "roast-301",
        postId: "post-3",
        authorId: "user-2",
        authorUsername: "NoMercy",
        authorDisplayName: "Marcus King",
        authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
        content: "Bro didn't take you out for dinner. He invited you as an unpaid financial sponsor for his fine-dining craving.",
        score: 1120,
        upvotes: 1140,
        downvotes: 20,
        createdAt: new Date(Date.now() - 3600 * 1000 * 13).toISOString(),
        isTopRoast: true,
      },
      {
        id: "roast-302",
        postId: "post-3",
        authorId: "user-4",
        authorUsername: "Cooked",
        authorDisplayName: "Leo Romero",
        authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
        content: "Subtracting the bread basket is generational broke-boy gymnastics. Put him in the Olympics.",
        score: 780,
        upvotes: 795,
        downvotes: 15,
        createdAt: new Date(Date.now() - 3600 * 1000 * 12).toISOString(),
      },
    ],
    comments: [],
  },
  {
    id: "post-4",
    authorId: "user-4",
    authorUsername: "Cooked",
    authorDisplayName: "Leo Romero",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
    isAnonymous: false,
    title: "Sent me an invoice for 'emotional labor & Netflix profile'",
    content: "Two weeks after we broke up, she emailed me a PDF invoice formatted in QuickBooks charging me $140 for 'two years of personalized life coaching' and $36.50 for using her Netflix Ultra HD profile during flu season.",
    category: "Breakup",
    hashtags: ["QuickBooksEx", "EmotionalInvoice", "ToxicRelationship"],
    createdAt: new Date(Date.now() - 3600 * 1000 * 26).toISOString(),
    reactions: { savage: 950, dead: 1680, redFlag: 720, deserved: 80 },
    roastsCount: 2,
    commentsCount: 29,
    savesCount: 210,
    sharesCount: 140,
    flameScore: 3100,
    roasts: [
      {
        id: "roast-401",
        postId: "post-4",
        authorId: "user-1",
        authorUsername: "HeartbreakDealer",
        authorDisplayName: "Elena Vance",
        authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
        content: "Email her back a countersuit for hazard pay and emotional restitution.",
        score: 520,
        upvotes: 535,
        downvotes: 15,
        createdAt: new Date(Date.now() - 3600 * 1000 * 24).toISOString(),
        isTopRoast: true,
      }
    ],
    comments: [],
  },
  {
    id: "post-5",
    authorId: "user-999",
    authorUsername: "anon_date_victim",
    authorDisplayName: "Anonymous",
    authorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80",
    isAnonymous: true,
    anonymousAlias: "The Escape Artist",
    title: "Faked a medical emergency to avoid introducing me to his mom",
    content: "We were walking into a family barbecue where his mom was hosting. He suddenly clutched his chest, fell to his knees in the driveway, gasped that his asthma was acting up, and had an Uber arrive in 3 minutes to drive him home. He does not have asthma.",
    category: "Worst Date",
    hashtags: ["AcademyAward", "FakeAsthma", "MomIssues", "Unbelievable"],
    createdAt: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
    reactions: { savage: 2200, dead: 3400, redFlag: 1500, deserved: 420 },
    roastsCount: 2,
    commentsCount: 91,
    savesCount: 940,
    sharesCount: 560,
    flameScore: 6900,
    roasts: [
      {
        id: "roast-501",
        postId: "post-5",
        authorId: "user-2",
        authorUsername: "NoMercy",
        authorDisplayName: "Marcus King",
        authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
        content: "Bro pre-ordered the Uber before he even clutched his chest. That wasn't an asthma attack, that was precision Broadway choreography.",
        score: 1450,
        upvotes: 1480,
        downvotes: 30,
        createdAt: new Date(Date.now() - 3600 * 1000 * 46).toISOString(),
        isTopRoast: true,
      }
    ],
    comments: [],
  }
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    userId: "user-1",
    actorId: "user-2",
    actorUsername: "NoMercy",
    actorDisplayName: "Marcus King",
    actorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    type: "roast_submitted",
    title: "New Roast Dropped 🔥",
    message: "@NoMercy dropped a savage roast on your LinkedIn story!",
    targetPostId: "post-1",
    createdAt: new Date(Date.now() - 3600 * 1000 * 2.5).toISOString(),
    read: false,
  },
  {
    id: "notif-2",
    userId: "user-1",
    actorId: "user-3",
    actorUsername: "SavageSam",
    actorDisplayName: "Samantha Reed",
    actorAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80",
    type: "post_reaction",
    title: "Post Going Viral 💀",
    message: "@SavageSam and 1,200 others reacted 💀 to your post.",
    targetPostId: "post-1",
    createdAt: new Date(Date.now() - 3600 * 1000 * 2.1).toISOString(),
    read: false,
  },
  {
    id: "notif-3",
    userId: "user-1",
    actorId: "user-5",
    actorUsername: "RedFlagHunter",
    actorDisplayName: "Chloe Bennett",
    actorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80",
    type: "user_followed",
    title: "New Follower",
    message: "@RedFlagHunter started following your stories.",
    createdAt: new Date(Date.now() - 3600 * 1000 * 5).toISOString(),
    read: true,
  },
  {
    id: "notif-4",
    userId: "user-1",
    actorId: "system",
    actorUsername: "exroast",
    actorDisplayName: "EX ROAST",
    actorAvatar: "",
    type: "achievement_unlocked",
    title: "Achievement Unlocked! 👑",
    message: "You unlocked the 'Roast King' badge for reaching top engagement!",
    createdAt: new Date(Date.now() - 3600 * 1000 * 12).toISOString(),
    read: true,
  }
];
